### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by WendyMcEff** [lynnxio/frontee-boilerplate-sandbox#1]
Installing starter kit
`statamic new frontee-boilerplate-sparkling-fog lynnxio/frontee-boilerplate`

is unable to find the package on Packagist
```
In PackageDiscoveryTrait.php line 379:
                                                                               
  Could not find a matching version of package lynnxio/frontee-boilerplate. C  
  heck the package spelling, your version constraint and that the package is   
  available in a stability which matches your minimum-stability (dev).         
                                                                               
Error installing starter kit [lynnxio/frontee-boilerplate].

In NewCommand.php line 476:
                                                                        
  There was a problem installing Statamic with the chosen starter kit!  
                                                                        
new [--dev] [--license [LICENSE]] [--local] [--with-config] [--without-dependencies] [--v2] [-f|--force] [--] <name> [<starter-kit>]
```

**Comment by rgbfreak** [comment]
I have the same issue

**Comment by jesseleite** [comment]
For this to be a 'starter kit', it needs to follow our starter kit export instructions, as documented here: https://statamic.dev/starter-kits/creating-a-starter-kit

**Comment by jesseleite** [comment]
@lynnxio For this to be a 'starter kit', you'll need to follow our starter kit export instructions, as documented here: https://statamic.dev/starter-kits/creating-a-starter-kit

**Comment by zunnurs01** [comment]
Not sure why I didn't receive any notification about this issue. I will fix it ASAP.

**Comment by zunnurs01** [comment]
The issue has been fixed https://github.com/lynnxio/frontee-boilerplate/commit/6f5917736452330afdcaa42a1f98f0e66496a959. This repo had been renamed for sandbox. Use https://github.com/lynnxio/frontee-boilerplate instead.
